project_id = "melusgrbbjgybhqkasoi"

[functions.aws-iot-simulator]
verify_jwt = false

[functions.sagemaker-ai-analytics]
verify_jwt = false

[functions.scada-operations]
verify_jwt = true

[functions.gis-copilot]
verify_jwt = true

[functions.environmental-data-processor]
verify_jwt = false

[functions.predictive-analytics-engine]
verify_jwt = false

[functions.mobile-field-sync]
verify_jwt = true

[functions.realtime-data-simulator]
verify_jwt = false

[functions.ai-analytics-processor]
verify_jwt = false

[functions.system-scheduler]
verify_jwt = false

[functions.alert-management-system]
verify_jwt = false