// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://melusgrbbjgybhqkasoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbHVzZ3JiYmpneWJocWthc29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzIzNzYsImV4cCI6MjA2ODU0ODM3Nn0.SZb6RgH-g85HTn_kVSsSZ4VGkwGuR4XRR94MqsFdPYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});